version: '3.1'

services:

  webgoat:
    image: webgoat/webgoat-8.0:latest
    container_name: "webgoat"
    environment:
      - WEBWOLF_HOST=webwolf
      - WEBWOLF_PORT=9090
    ports:
      - "7080:8080"
      - "9001:9001"
    restart: "always"
    volumes:
      - ./data/webgoat:/home/webgoat/.webgoat
  
  webwolf:
    image: webgoat/webwolf:latest
    container_name: "webwolf"
    ports:
      - "7090:9090"
    restart: "always"
    command: --spring.datasource.url=jdbc:hsqldb:hsql://webgoat:9001/webgoat --server.address=0.0.0.0
